version: 0.0

os: linux

files:
  - source: /artifacts/dist
    destination: /opt
    overwrite: true

permissions:
  - object: /opt
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: /artifacts/scripts/after_install.sh
      timeout: 300
      runas: root
