version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    
    commands:
      - npm install

  build:
    commands:
      - ng build

artifacts:
files:
  - public/**/*
  - src/**/*
  - package.json
  - appspec.yml
  - scripts/**/*
