version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    
    commands:
      - npm install && npm install -g @angular/cli

  build:
    commands:
      - ng build
      - mkdir -p ${CODEBUILD_SRC_DIR}/artifacts
      - cp -r dist/ scripts/ package.json ${CODEBUILD_SRC_DIR}/artifacts/

artifacts:
  files:
    - artifacts/**/*
    - appspec.yml
